# Generated by Django 6.0.2 on 2026-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Products"},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="inventory_p_sku_f85905_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="inventory_p_categor_607069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["stock_quantity"], name="inventory_p_stock_q_e1fd3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="inventory_p_created_711f60_idx"
            ),
        ),
    ]
