# Generated by Django 6.0.2 on 2026-02-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_stockmovement_sales"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="inventory_p_created_711f60_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="inventory_p_created_081871_idx"
            ),
        ),
    ]
