# Generated by Django 6.0.2 on 2026-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_product_inventory_p_created_711f60_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
