# Generated by Django 6.0.2 on 2026-02-28 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_stockmovement_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 558893, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 558909, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 559732, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 559741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 560639, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 559211, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 559220, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
