# Generated by Django 6.0.2 on 2026-03-05 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0009_alter_category_created_at_alter_category_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 5, 15, 23, 35, 787215, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 3, 5, 15, 23, 35, 787239, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
