# Generated by Django 6.0.2 on 2026-02-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
