# Generated by Django 6.0.2 on 2026-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sales_created_at_alter_sales_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
