# Generated by Django 6.0.2 on 2026-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sales_created_at_alter_sales_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesitem",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
