# Generated by Django 6.0.2 on 2026-02-28 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_salesitem_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 561615, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 561956, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 561965, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 2, 28, 7, 32, 32, 563005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
