# Generated by Django 6.0.2 on 2026-03-04 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_customer_created_at_alter_sales_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
